### ISSUE TITLE
我把整个Demo下载，在IE11中还是显示空白，谷歌可以正常显示

### ISSUE THREAD

**Issue by renff** [lanux/Vue-Admin#10]

**Comment by lanux** [comment]
webpack.base.conf.js 里面有没有下面这段？ 然后改成你自己的element-ui版本号。
{
test: /.js$/,
loader: 'babel-loader',
//exclude: /(node_modules|bower_components)/,
// 注意elementUI的源码使用ES6需要解析
include: [
resolve('src'),
resolve('test'),
resolve('/node_modules/.1.4.8@element-ui/src'),
resolve('/node_modules/.1.4.8@element-ui/packages'),
resolve('/node_modules/.4.3.0@vuex-router-sync')
]
},


@renff
