### ISSUE TITLE
空白页面

### ISSUE THREAD

**Issue by sunshadowyq** [lanux/Vue-Admin#2]
hello，我用npm run build的页面打开是空白的，请问您试过吗，能不能帮忙看下？生成后，index的代码如下
`<!DOCTYPE html><html><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><title>Vue-Admin-Demo</title><meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" name=viewport><link href=/Vue-Admin/static/css/app.af5943e03a354b9a94773039e8ab62d5.css rel=stylesheet></head><body class="hold-transition skin-blue sidebar-mini"><div id=root></div><script type=text/javascript src=/Vue-Admin/static/js/manifest.b5747c1e8182a279d0fa.js></script><script type=text/javascript src=/Vue-Admin/static/js/vendor.8f9111dea9329da687ed.js></script><script type=text/javascript src=/Vue-Admin/static/js/app.a2e81010c4c4aba21c9f.js></script></body></html>`

**Comment by lanux** [comment]
## 1.first

>   Tip: built files are meant to be served over an HTTP server.
>   Opening index.html over file:// won't work.

## 2.second
nginx config example：
```
server {
	listen       80;
	server_name 127.0.0.1 localhost;
	access_log  logs/host.access.log;

	location /Vue-Admin {
		rewrite ^/Vue-Admin(.*) $1 last;
	}

	location / {
		root   E:\git\github\Vue-Admin\dist;
		index  index.html index.htm;
	}
}
		
```

## 3.third
edit file **[./Vue-Admin/src/api.js](https://github.com/lanux/Vue-Admin/blob/master/src/api.js)**
```
export const CONTEXT = '';
// export const CONTEXT = './Vue-Admin';
...
```

**Comment by sunshadowyq** [comment]
非常感谢，今天回家，重新查看了代码，发现index载入css等资源时，均引用/Vue-admin/static目录的资源，但npm run build生成的资源实在/static目录下，因为修改了config/index.js下module.exports.build.assetsPublicPath值，从"Vue-admin"改成了“”，这样就可以了

**Comment by lanux** [comment]
thx,i forgot about it
