### ISSUE TITLE
项目clone成功，不能成功运行

### ISSUE THREAD

**Issue by wangyano0** [lanux/Vue-Admin#3]
由于图片上传不成功， 控制台报错  Uncaught SyntaxError: Unexpected token ...        还想请问楼主，需要改代码是否才能在本地运行成功？ 如果更改代码，是在哪更改呢

**Comment by lanux** [comment]
本地可以运行成功的啊，你是不是版本问题？npm install报错么？

**Comment by wangyano0** [comment]
npm install 不会报错，npm run dev  也不会报错，但是在浏览器运行得时候，页面没有任何效果，控制台报错

**Comment by lanux** [comment]
不要用360浏览器，用chrome或者firefox试试。vue对旧版本ie内核是不支持的
