### ISSUE TITLE
请问侧边栏能够收起来吗？

### ISSUE THREAD

**Issue by edwinhuish** [lanux/Vue-Admin#5]
请问侧边栏能够收起来，并做成下面这种形式么?

![image](https://user-images.githubusercontent.com/5207925/28246574-a5cee85a-6a4f-11e7-8826-a79fe0a44379.png)

**Comment by lanux** [comment]
谢谢，肯定是可以的。只是最近有点忙，没时间搞...迟点有空搞一个，类似[antd-admin](http://zuiidea.github.io/antd-admin)那种。

**Comment by edwinhuish** [comment]
我能可耻的问一下，文件层次结构能否参考这个项目？

这个文件结构很清晰。。

[PanJiaChen/vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)

**Comment by lanux** [comment]
侧边栏收起已增加
